apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # En este caso, añadimos un usuario local con los privilegios apikey y login
  #   apiKey: permite generar claves API
  #   login: permite iniciar sesión en la interfaz de usuario
  accounts.lara: apiKey, login
